version: '3'

services:
  api-gateway:
    image: nginx:latest
    container_name: api-gateway
    ports:
      - "80:80"
    networks:
      - gateway-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - controle-lancamentos
      - consolidado-report
      - autenticacao  # Adicionado o novo serviço

  controle-lancamentos:
    build:
      context: ./ControleDeLancamentos
    expose:
      - "80"
    networks:
      - gateway-network
    depends_on:
      - controle-lancamentos-db
      - rabbitmq

  controle-lancamentos-db:
    image: postgres:latest
    container_name: controle-lancamentos-db
    environment:
      - POSTGRES_DB=controle_lancamentos_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pass

  consolidado-report:
    build:
      context: ./ConsolidadoDiario
    expose:
      - "80"
    networks:
      - gateway-network
    depends_on:
      - consolidado-report-redis
      - rabbitmq
    environment:
      - REDIS_HOST=consolidado-report-redis
      - REDIS_PORT=6379

  consolidado-report-redis:
    image: "redis:latest"
    container_name: consolidado-report-redis
    ports:
      - "6379:6379"

  autenticacao:
    build:
      context: ./Autenticacao 
    expose:
      - "80"
    networks:
      - gateway-network
    depends_on:
      - autenticacao-db
      - rabbitmq

  autenticacao-db:
    image: postgres:latest
    container_name: autenticacao-db
    environment:
      - POSTGRES_DB=autenticacao_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pass

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "rabbitmq_data:/data"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=pass

networks:
  gateway-network:
    driver: bridge

volumes:
  rabbitmq_data:
